package com.cx1337.nine_nether_regions.datagen;

import com.cx1337.nine_nether_regions.NineNetherRegions;
import com.cx1337.nine_nether_regions.block.ModBlocks;
import com.cx1337.nine_nether_regions.item.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class ModEnUsLangProvider extends LanguageProvider {
    public ModEnUsLangProvider(PackOutput output) {
        super(output, NineNetherRegions.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add(ModItems.DAMAGE_TEST.get(), "§kDamage Test Sword");
        add(ModItems.ALLOY_HILT.get(), "Alloy Hilt");
        add(ModItems.AMETHYST_BEETROOT.get(), "Amethyst Beetroot");
        add(ModItems.CAVES_MUSIC_DISC.get(), "Music Disc--Biomes/Caves");
        add(ModItems.GHOSTLIUM_APPLE.get(), "Ghostlium Apple");
        add(ModItems.ENCHANTED_GHOSTLIUM_APPLE.get(), "Enchanted Ghostlium Apple");
        add(ModItems.AMETHYST_DAGGER.get(), "Amethyst Dagger");
        add(ModItems.BLOODBLADE_ESSENCE.get(), "Bloodblade Essence");
        add(ModItems.BLOODBLADE_PEAK_MUSIC_DISC.get(), "Music Disc--Biomes/Bloodblade Peak");
        add(ModItems.CHERRY_STICK.get(), "§d Cherry Stick");
        add(ModItems.CHERRY_HELMET.get(), "§d Cherry Helmet");
        add(ModItems.CHERRY_CHESTPLATE.get(), "§d Cherry Chestplate");
        add(ModItems.CHERRY_LEGGINGS.get(), "§d Cherry Leggings");
        add(ModItems.CHERRY_BOOTS.get(), "§d Cherry Boots");
        add(ModItems.STYX_FERRYMAN_MUSIC_DISC.get(), "Music Disc--Styx Ferryman");
        add(ModItems.DIAMOND_BOWSTRING.get(), "Diamond Bowstring");
        add(ModItems.EMPTY_FABRIC.get(), "Empty Fabric");
        add(ModItems.FLUORESCENCE_FOREST_MUSIC_DISC.get(), "Music Disc--Biomes/Fluorescence Forest");
        add(ModItems.MAGIC_FABRIC.get(), "Magic Fabric");
        add(ModItems.MANJUSAKA_PLAIN_MUSIC_DISC.get(), "Music Disc--Biomes/Manjusaka Plain");
        add(ModItems.STYX_FABRIC.get(), "Styx Fabric");
        add(ModItems.GHOSTLIUM.get(), "Ghostlium");
        add(ModItems.HELLALLOY_INGOT.get(), "§aHellalloy Ingot");
        add(ModItems.HELLALLOY_AXE.get(), "§aHellalloy Axe");
        add(ModItems.HELLALLOY_HOE.get(), "§aHellalloy Hoe");
        add(ModItems.HELLALLOY_PICKAXE.get(), "§aHellalloy Pickaxe");
        add(ModItems.HELLALLOY_SHOVEL.get(), "§aHellalloy Shovel");
        add(ModItems.HELLALLOY_HELMET.get(), "§aHellalloy Helmet");
        add(ModItems.HELLALLOY_CHESTPLATE.get(), "§aHellalloy Chestplate");
        add(ModItems.HELLALLOY_LEGGINGS.get(), "§aHellalloy Leggings");
        add(ModItems.HELLALLOY_BOOTS.get(), "§aHellalloy Boots");
        add(ModItems.HELLALLOY_SWORD.get(), "§aHellalloy Sword");
        add(ModItems.HELLALLOY_LONGBOW.get(), "§aHellalloy Longbow");
        add(ModItems.HELLALLOY_ROD.get(), "§aHellalloy Rod");
        add(ModItems.NETHERITE_ROD.get(), "Netherite Rod");
        add(ModItems.STYX_INGOT.get(), "§5§lStyx Ingot");
        add(ModItems.STYX_TEAR.get(), "§4§lStyx Tear");
        add(ModItems.STYX_SWORD.get(), "§4§lStyx Battle-sword");
        add(ModItems.STYX_PICKAXE.get(), "§4Styx Pickaxe");
        add(ModItems.STYX_HELMET.get(), "§4Styx Helmet");
        add(ModItems.STYX_CHESTPLATE.get(), "§4Styx Chestplate");
        add(ModItems.STYX_LEGGINGS.get(), "§4Styx Leggings");
        add(ModItems.STYX_BOOTS.get(), "§4Styx Boots");
        add(ModItems.STEEL_BASE.get(), "Steel Base");
        add(ModItems.STEEL_INGOT.get(), "Steel Ingot");
        add(ModItems.STEEL_NUGGET.get(), "Steel Nugget");
        add(ModItems.STEEL_AXE.get(), "Steel Axe");
        add(ModItems.STEEL_HOE.get(), "Steel Hoe");
        add(ModItems.STEEL_PICKAXE.get(), "Steel Pickaxe");
        add(ModItems.STEEL_SHOVEL.get(), "Steel Shovel");
        add(ModItems.STEEL_SWORD.get(), "Steel Sword");
        add(ModItems.STEEL_HELMET.get(), "Steel Helmet");
        add(ModItems.STEEL_CHESTPLATE.get(), "Steel Chestplate");
        add(ModItems.STEEL_LEGGINGS.get(), "Steel Leggings");
        add(ModItems.STEEL_BOOTS.get(), "Steel Boots");
        add(ModItems.STEEL_HORSE_ARMOR.get(), "Steel Horse Armor");
        add(ModItems.COPPER_NUGGET.get(), "Copper Nugget");
        add(ModItems.COPPER_AXE.get(), "Copper Axe");
        add(ModItems.COPPER_HOE.get(), "Copper Hoe");
        add(ModItems.COPPER_PICKAXE.get(), "Copper Pickaxe");
        add(ModItems.COPPER_SHOVEL.get(), "Copper Shovel");
        add(ModItems.COPPER_SWORD.get(), "Copper Sword");
        add(ModItems.COPPER_HELMET.get(), "Copper Helmet");
        add(ModItems.COPPER_CHESTPLATE.get(), "Copper Chestplate");
        add(ModItems.COPPER_LEGGINGS.get(), "Copper Leggings");
        add(ModItems.COPPER_BOOTS.get(), "Copper Boots");
        add(ModItems.COPPER_HORSE_ARMOR.get(), "Copper Horse Armor");
        add(ModItems.WEB_BALL.get(), "Web Ball");
        add(ModItems.WOOD_HELMET.get(), "Wood Helmet");
        add(ModItems.WOOD_CHESTPLATE.get(), "Wood Chestplate");
        add(ModItems.WOOD_LEGGINGS.get(), "Wood Leggings");
        add(ModItems.WOOD_BOOTS.get(), "Wood Boots");
        add(ModItems.ENDER_STAFF.get(), "Ender Teleport Staff");
        add(ModItems.FIRE_CORE.get(), "Fire Core");
        add(ModItems.FIRE_STAFF.get(), "Fire Staff");
        add(ModItems.WITHER_CORE.get(), "Wither Core");
        add(ModItems.WITHER_STAFF.get(), "Wither Staff");
        add(ModItems.VOID_CORE.get(), "Void Core");
        add(ModItems.VOID_STAFF.get(), "Void Staff");
        add(ModItems.VOID_SHARD.get(), "Void Shard");
        add(ModItems.VOIDRITE_INGOT.get(), "Voidrite Ingot");
        add(ModItems.VOIDRITE_UPGRADE_SMITHING_TEMPLATE.get(), "Smithing Template");
        add(ModItems.VOIDRITE_ROD.get(), "Voidrite Rod");
        add(ModItems.VOIDRITE_AXE.get(), "Voidrite Axe");
        add(ModItems.VOIDRITE_HOE.get(), "Voidrite Hoe");
        add(ModItems.VOIDRITE_PICKAXE.get(), "Voidrite Pickaxe");
        add(ModItems.VOIDRITE_SHOVEL.get(), "Voidrite Shovel");
        add(ModItems.VOIDRITE_SWORD.get(), "Voidrite Sword");
        add(ModItems.VOIDRITE_HELMET.get(), "Voidrite Helmet");
        add(ModItems.VOIDRITE_CHESTPLATE.get(), "Voidrite Chestplate");
        add(ModItems.VOIDRITE_LEGGINGS.get(), "Voidrite Leggings");
        add(ModItems.VOIDRITE_BOOTS.get(), "Voidrite Boots");
        add(ModItems.RUBY.get(), "Ruby");
        add(ModItems.RAINBOWGEM.get(), "Rainbow Jade");
        add(ModItems.RAINBOWGEM_AXE.get(), "Rainbow Jade Axe");
        add(ModItems.RAINBOWGEM_HOE.get(), "Rainbow Jade Hoe");
        add(ModItems.RAINBOWGEM_PICKAXE.get(), "Rainbow Jade Pickaxe");
        add(ModItems.RAINBOWGEM_SHOVEL.get(), "Rainbow Jade Shovel");
        add(ModItems.RAINBOWGEM_SWORD.get(), "Rainbow Jade Sword");
        add(ModItems.RUBY_SWORD.get(), "Ruby Sword");
        add(ModItems.RAINBOWGEM_HELMET.get(), "Rainbow Jade Helmet");
        add(ModItems.RAINBOWGEM_CHESTPLATE.get(), "Rainbow Jade Chestplate");
        add(ModItems.RAINBOWGEM_LEGGINGS.get(), "Rainbow Jade Leggings");
        add(ModItems.RAINBOWGEM_BOOTS.get(), "Rainbow Jade Boots");
        add(ModItems.THE_STYX_MUSIC_DISC.get(), "Music Disc--Biomes/The Styx,Underworld Plains");
        add(ModItems.UNDERWORLD_BRICK.get(), "Underworld Brick");
        add(ModItems.UNDERWORLD_CRYSTAL.get(), "§bUnderworld Crystal");
        add(ModItems.UNDERWORLD_ABYSS_MUSIC_DISC.get(), "Music Disc--Biomes/Underworld Abyss");

        add(ModBlocks.BLOODY_SAND.get(), "Bloody Sand");
        add(ModBlocks.BLOODBLADE_ORE.get(), "§4Bloodblade_ore");
        add(ModBlocks.BLOODBLADE_ROCK.get(), "Bloodblade Rock");
        add(ModBlocks.CRACKED_BLOODBLADE_ROCK.get(), "Cracked Bloodblade Rock");
        add(ModBlocks.HARDENED_BLOODBLADE_ROCK.get(), "Hardened Bloodblade Rock");
        add(ModBlocks.COMPACT_OBSIDIAN.get(), "Compact Obsidian");
        add(ModBlocks.REINFORCED_OBSIDIAN.get(), "Reinforced Obsidian");
        add(ModBlocks.FLUOROSCOPY_BLOCK.get(), "Fluoroscopy Block");
        add(ModBlocks.GLOWING_UNDERWORLD_BRICKS.get(), "§bGlowing Underworld Bricks");
        add(ModBlocks.GLOWING_UNDERWORLD_BRICK_SLAB.get(), "§bGlowing Underworld Brick Slab");
        add(ModBlocks.GLOWING_UNDERWORLD_BRICK_STAIRS.get(), "§bGlowing Underworld Brick Stairs");
        add(ModBlocks.HELLALLOY_BLOCK.get(), "§aHellalloy Block");
        add(ModBlocks.HELLIGHT.get(), "Hellight");
        add(ModBlocks.HELL_NUCLEUS.get(), "§c§lHell Nucleus");
        add(ModBlocks.HELLWOOD_LOG.get(), "Hellwood Log");
        add(ModBlocks.HELLWOOD_WOOD.get(), "Hellwood Wood");
        add(ModBlocks.STRIPPED_HELLWOOD_LOG.get(), "Stripped Hellwood Log");
        add(ModBlocks.STRIPPED_HELLWOOD_WOOD.get(), "Stripped Hellwood Wood");
        add(ModBlocks.HELLWOOD_PLANKS.get(), "Hellwood Planks");
        add(ModBlocks.HELLWOOD_LEAVES.get(), "Hellwood Leaves");
        add(ModBlocks.HELLWOOD_SAPLING.get(), "Hellwood Sapling");
        add(ModBlocks.HELLWOOD_BUTTON.get(), "Hellwood Button");
        add(ModBlocks.HELLWOOD_FENCE.get(), "Hellwood Fence");
        add(ModBlocks.HELLWOOD_FENCE_GATE.get(), "Hellwood Fence Gate");
        add(ModBlocks.HELLWOOD_DOOR.get(), "Hellwood Door");
        add(ModBlocks.HELLWOOD_TRAPDOOR.get(), "Hellwood Trapdoor");
        add(ModBlocks.HELLWOOD_PRESSURE_PLATE.get(), "Hellwood Pressure Plate");
        add(ModBlocks.HELLWOOD_STAIRS.get(), "Hellwood Stairs");
        add(ModBlocks.HELLWOOD_SLAB.get(), "Hellwood Slab");
        add(ModBlocks.MANJUSAKA.get(), "§cManjusaka");
        add(ModBlocks.PINESAP.get(), "Pinesap");
        add(ModBlocks.POTTED_PINESAP.get(), "Potted Pinesap");
        add(ModBlocks.POTTED_HELLWOOD_SAPLING.get(), "Potted Hellwood Sapling");
        add(ModBlocks.NULL_BLOCK.get(), "§c§k?????");
        add(ModBlocks.NULL_GRASSBLOCK.get(), "§c§k!!!!!");
        add(ModBlocks.STYX_BLOCK.get(), "§5§lStyx Block");
        add(ModBlocks.HELL_LAMP.get(), "Hell Lamp");
        add(ModBlocks.STYX_LAMP.get(), "§4Styx Lamp");
        add(ModBlocks.CARVED_WINDOW.get(), "Carved Window");
        add(ModBlocks.UW_CARVED_WINDOW.get(), "§bUnderworld Carved Window");
        add(ModBlocks.STEEL_BLOCK.get(), "Steel Block");
        add(ModBlocks.RUBY_BLOCK.get(), "Ruby Block");
        add(ModBlocks.RAINBOWGEM_BLOCK.get(), "Rainbowgem Block");
        add(ModBlocks.UNDERWORLDRACK.get(), "Underworldrack");
        add(ModBlocks.UNDERWORLD_BRICKS.get(), "Underworld Bricks");
        add(ModBlocks.UNDERWORLD_BRICK_BUTTON.get(), "Underworld Brick Button");
        add(ModBlocks.UNDERWORLD_BRICK_FENCE.get(), "Underworld Brick Fence");
        add(ModBlocks.UNDERWORLD_BRICK_FENCE_GATE.get(), "Underworld Brick Fence Gate");
        add(ModBlocks.UNDERWORLD_BRICK_SLAB.get(), "Underworld Brick Slab");
        add(ModBlocks.UNDERWORLD_BRICK_STAIRS.get(), "Underworld Brick Stairs");
        add(ModBlocks.UNDERWORLD_BRICK_WALL.get(), "Underworld Brick Wall");
        add(ModBlocks.UNDERWORLD_SPIRIT_STONE.get(), "Underworld Spirit Stone");
        add(ModBlocks.UNDERWORLD_CRYSTAL_ORE.get(), "Underworld Crystal ore");
        add(ModBlocks.VOID_NEBULA.get(), "Void Nebula");
        add(ModBlocks.VOIDRITE_BLOCK.get(), "Voidrite Block");

        add("effect.nine_nether_regions.decline", "Decline");
        add("item.minecraft.potion.effect.decline_potion", "Decline Potion");
        add("item.minecraft.splash_potion.effect.decline_potion", "Decline Splash Potion");
        add("item.minecraft.lingering_potion.effect.decline_potion", "Decline Lingering Potion");
        add("item.minecraft.potion.effect.s_decline_potion", "Strengthened Decline Potion");
        add("item.minecraft.splash_potion.effect.s_decline_potion", "Strengthened Decline Splash Potion");
        add("item.minecraft.lingering_potion.effect.s_decline_potion", "Strengthened Decline Lingering Potion");
        add("death.attack.decline", "%1$s was dissipated into the wind");
        add("death.attack.decline.player", "%1$s faded away while fighting with %2$s");
        add("effect.nine_nether_regions.bloodblade_curse", "Bloodblade Curse");
        add("item.minecraft.potion.effect.bb_curse_potion", "Bloodblade Curse Potion");
        add("item.minecraft.splash_potion.effect.bb_curse_potion", "Bloodblade Curse Splash Potion");
        add("item.minecraft.lingering_potion.effect.bb_curse_potion", "Bloodblade Curse Lingering Potion");
        add("item.minecraft.potion.effect.s_bb_curse_potion", "Strengthened Bloodblade Curse Potion");
        add("item.minecraft.splash_potion.effect.s_bb_curse_potion", "Strengthened Bloodblade Curse Splash Potion");
        add("item.minecraft.lingering_potion.effect.s_bb_curse_potion", "Strengthened Bloodblade Curse Lingering Potion");
        add("effect.nine_nether_regions.spider_climb", "Spider Climb");
        add("effect.nine_nether_regions.frost", "Frost");
        add("item.minecraft.potion.effect.frost_potion", "Frost Potion");
        add("item.minecraft.splash_potion.effect.frost_potion", "Frost Splash Potion");
        add("item.minecraft.lingering_potion.effect.frost_potion", "Frost Lingering Potion");
        add("item.minecraft.potion.effect.s_frost_potion", "Strengthened Frost Potion");
        add("item.minecraft.splash_potion.effect.s_frost_potion", "Strengthened Frost Splash Potion");
        add("item.minecraft.lingering_potion.effect.s_frost_potion", "Strengthened Frost Lingering Potion");
        add("effect.nine_nether_regions.wrapped", "Wrapped");
        add("effect.nine_nether_regions.hell_blast", "Hell Blast");

        add("enchantment.nine_nether_regions.storm_anger", "Anger of Storm");
        add("enchantment.nine_nether_regions.soul_rip", "Soul Rip");

        add("painting.nine_nether_regions.wayfarer.title", "Wayfarer");
        add("painting.nine_nether_regions.wayfarer.author", "CX1337");
        add("painting.nine_nether_regions.the_sword.title", "The Sword");
        add("painting.nine_nether_regions.the_sword.author", "05Z08");

        add("itemGroup.nine_nether_regions_materials_tab", "§2§lNnR:items");
        add("itemGroup.nine_nether_regions_blocks_tab", "§2§lNnR:blocks");

        add("item.nine_nether_regions.styx_ferryman_music_disc.desc", "Rafael Krux--Dawn of the Apocalypse");
        add("item.nine_nether_regions.bloodblade_peak_music_disc.desc", "Rafael Krux--Lonely Mountain");
        add("item.nine_nether_regions.underworld_abyss_music_disc.desc", " Bryan Teoh--Mysterious Lights");
        add("item.nine_nether_regions.the_styx_music_disc.desc", "Bryan Teoh--Think About It");
        add("item.nine_nether_regions.fluorescence_forest_music_disc.desc", "Kevin MacLeod--Night Vigil");
        add("item.nine_nether_regions.manjusaka_plain_music_disc.desc", "Bryan Teoh--Go On Without Me");
        add("item.nine_nether_regions.caves_music_disc.desc", "Kevin MacLeod--Satin Danger");

        add("advancement.nine_nether_regions.root.title", "Nine-nether Regions");
        add("advancement.nine_nether_regions.root.description", "The beginning of your journey.");
        add("advancement.nine_nether_regions.safe.title", "Safe?");
        add("advancement.nine_nether_regions.safe.description", "Obtain a full set of Wood armor.");
        add("advancement.nine_nether_regions.different_set.title", "A Different Set!");
        add("advancement.nine_nether_regions.different_set.description", "Obtain a full set of Cherry armor,a variant of Wood armor.");
        add("advancement.nine_nether_regions.better_than_iron.title", "Better than Iron");
        add("advancement.nine_nether_regions.better_than_iron.description", "Get Steel Ingot.");
        add("advancement.nine_nether_regions.better_protection.title", "Better Protection");
        add("advancement.nine_nether_regions.better_protection.description", "Obtain a Steel armor.");
        add("advancement.nine_nether_regions.beating_energy.title", "Beating Energy");
        add("advancement.nine_nether_regions.beating_energy.description", "Obtain Underworld Crystal.");
        add("advancement.nine_nether_regions.deep_in_the_dark.title", "Deep In The Dark");
        add("advancement.nine_nether_regions.deep_in_the_dark.description", "Obtain Ghostlium.");
        add("advancement.nine_nether_regions.shining.title", "It's Shining!");
        add("advancement.nine_nether_regions.shining.description", "Get Rainbow Jade.");
        add("advancement.nine_nether_regions.dazzling.title", "Dazzling!");
        add("advancement.nine_nether_regions.dazzling.description", "Obtain a Rainbow Jade armor.");
        add("advancement.nine_nether_regions.voidrite_ingot.title", "Void Forging");
        add("advancement.nine_nether_regions.voidrite_ingot.description", "Obtain a piece of Voidrite Ingot.");
        add("advancement.nine_nether_regions.voidrite_armor.title", "Void Your Body");
        add("advancement.nine_nether_regions.voidrite_armor.description", "Obtain a Voidrite armor.");
        add("advancement.nine_nether_regions.vampire.title", "Fragile Vampire");
        add("advancement.nine_nether_regions.vampire.description", "Obtain a Ruby Sword.");
        add("advancement.nine_nether_regions.hell_archive.title", "Archive of Underworld");
        add("advancement.nine_nether_regions.hell_archive.description", "Get Hellalloy Ingot.");
        add("advancement.nine_nether_regions.hellalloy_set.title", "Hellalloy Protection");
        add("advancement.nine_nether_regions.hellalloy_set.description", "Obtain a full set of Hellalloy armor.");
        add("advancement.nine_nether_regions.styx_tear.title", "Abyssal Grudge");
        add("advancement.nine_nether_regions.styx_tear.description", "Obtain Styx Tear.");
        add("advancement.nine_nether_regions.styx_ingot.title", "The Thirteenth River...");
        add("advancement.nine_nether_regions.styx_ingot.description", "Get Styx Ingot.");
        add("advancement.nine_nether_regions.styx_set.title", "Styx Soul Forged");
        add("advancement.nine_nether_regions.styx_set.description", "Obtain a full set of Styx armor.");

        add("tooltip.nine_nether_regions.amethyst_dagger", "§3§oAlthough this short sword is indeed small, the recipe is simple, and the attack power is not high, thanks to the vitality contained in amethyst, players have a 33% chance of recovering 1 point of health each time they use it to attack. Meanwhile, precisely because of its compact size, players can swing it faster.\nOf course, due to the fragility of amethyst itself, the durability of this short sword is not as high.");
        add("tooltip.nine_nether_regions.ghostlium_apple", "§3§o Tainted with a bit of the Underworld's power... but it tastes delicious!");
        add("tooltip.nine_nether_regions.enchanted_ghostlium_apple", "§3§oAn Enchanted Golden Apple, enhanced in every way by the Underworld's power. Delicious, filling, and incredibly potent.");
        add("tooltip.nine_nether_regions.web_fruit", "§3§oThe Web Ball neutralizes the teleportation ability of Chorus Fruit, while granting players wall-climbing capabilities similar to spiders for a limited time.");
        add("tooltip.nine_nether_regions.bloodblade_essence", "§3§oAn indescribable mass of matter…… but the energy contained within should not be underestimated.");
        add("tooltip.nine_nether_regions.hellalloy_block", "§3§oFilled with the Power From the Underworld.");
        add("tooltip.nine_nether_regions.hellalloy_ingot", "§3§oStrengthened by the Power of the Underworld,the Alloy Ingot is Incredibly Hard.");
        add("tooltip.nine_nether_regions.hellalloy_pickaxe", "§3§oOh,Obsidian,in my eyes,you're just a stone~");
        add("tooltip.nine_nether_regions.hellalloy_shovel", "§3§oDo you want this world to be BARREN?");
        add("tooltip.nine_nether_regions.hellalloy_axe", "§3§oMaybe Logger Vick needs it.");
        add("tooltip.nine_nether_regions.hellalloy_hoe", "§3§oPrincipal's hoe.");
        add("tooltip.nine_nether_regions.hellalloy_sword_alt", "§3§oThis Sword is no longer a sword in the sense of Minecraft.\nThanks to the superior materials, All damage caused by this sword is AOE.\nUnfortunately, this material is not that top-notch. So the AOE damage does not increase with the enhancement of attributes such as Enchantments.\nIn addition, thanks to the power of the embedded crystal nucleus, this sword can automatically repair after damage.");
        add("tooltip.nine_nether_regions.hellalloy_sword", "§3§oPress§r §6§oAlt§r§3§o to display more.");
        add("tooltip.nine_nether_regions.hell_nucleus", "§3§oJust like the hot core of a star, it's scorching hot.");
        add("tooltip.nine_nether_regions.styx_fabric", "§3§oFilled with Styx Ferryman's soul.");
        add("tooltip.nine_nether_regions.styx_tear", "§5§o The blood tears of Styx Ferryman, containing her endless sorrow... as well as a part of her power.");
        add("tooltip.nine_nether_regions.styx_block", "§3§oAlmost Unbreakable.Only §kBedrock§r§3§o and §k???§r§3§o is Harder.Even §kWither??§r§3§o can't Destroy It.");
        add("tooltip.nine_nether_regions.styx_ingot", "§3§oJust Like Styx Ferryman's Will.Unbreakable.");
        add("tooltip.nine_nether_regions.styx_sword", "§3§oPress§r §6§oAlt§r§3§o to display more.");
        add("tooltip.nine_nether_regions.styx_sword_alt",
                "§6§oIndestructible: §r§3§oUnder normal circumstances, this weapon's durability is not consumed. If the weapon's durability is damaged by some means, it will recover very quickly (42 points per 4 ticks).\n§r§6§oBattle-sword's Edge: §r§3§oWhen attacking a creature, the Styx Battle-sword simultaneously deals area damage to all non-friendly creatures within a 4-block radius centered on the player, dealing §r§e§o(Battle-sword's attack power + target's max health × 5%) §r§3§o damage.\n§r§6§oSoul Siphon: §r§3§oEach time the battle-sword attacks, it forcibly restores §r§d§o(player's max health × 8%) §r§3§o health to the player.\n§r§4§oWarning: Due to changes in this sword's attack mechanics, most utility enchantments (such as Sharpness, Smite) will likely have no effect on it!");
        add("tooltip.nine_nether_regions.styx_pickaxe", "§3§oPress§r §6§oAlt§r§3§o to display more.");
        add("tooltip.nine_nether_regions.styx_pickaxe_alt", "§3§oThis pickaxe is the best among all pickaxes.\nUnder normal circumstances, its durability cannot be consumed. If under special circumstances its durability is reduced, it will rapidly restore to full durability (restores 24 points per 4 ticks).\nBlessed by the power of Styx, this pickaxe breaks any block 2.5 times faster than normal, and when breaking any block, there is a 24% chance to drop a diamond and a 12% chance to drop a netherite scrap.");
        add("tooltip.nine_nether_regions.steel_base", "§3§oAfter a thousand trials and tribulations, one can obtain a good piece of steel.");
        add("tooltip.nine_nether_regions.steel_ingot", "§3§oBetter than iron.");
        add("tooltip.nine_nether_regions.rainbowgem_armors", "§3§oAll set Bonus: 7% damage reduction against nearly all damage types.");
        add("tooltip.nine_nether_regions.voidrite_armors", "§3§oAll set Bonus: 18% damage reduction against nearly all damage types.");
        add("tooltip.nine_nether_regions.alloy_hilt", "§3§oIt can be used as a Weapon.BUT that's by no means its true purpose.");
        add("tooltip.nine_nether_regions.hellalloy_helmet_alt",
                "§3§oSelf healing: If the durability is not sufficient, the equipment will automatically restore durability in the armor bar or player backpack §1(4 points restored every 2 seconds)§r§3§o.\nSingle effect: When equipped on the armor bar, it continuously provides players with §6night_vision§r§3§o(effect level:1), while clearing §7blindness§r§3§o and §7darkness§r§3§o effects on the player's body.\nComplete set of effects: Provide a 44% reduction for most damages,force to restore 0.7 point of health for every 10 ticks and provide §6resistance§r§3§o(level 2) effect.");
        add("tooltip.nine_nether_regions.hellalloy_helmet", "§3§oPress§r §6§oAlt§r§3§o to display more.");
        add("tooltip.nine_nether_regions.hellalloy_chestplate_alt",
                "§3§oSelf healing: If the durability is not sufficient, the equipment will automatically restore durability in the armor bar or player backpack §1(4 points restored every 2 seconds)§r§3§o.\nSingle effect: When equipped on the armor bar, it continuously provides players with §6fire_resistance§r§3§o, while clearing §7wither§r§3§o, §7poison§r§3§o and §7mining_fatigue§r§3§o effects on the player's body.\nComplete set of effects: Provide a 44% reduction for most damages,force to restore 0.7 point of health for every 10 ticks and provide §6resistance§r§3§o(level 2) effect.");
        add("tooltip.nine_nether_regions.hellalloy_chestplate", "§3§oPress§r §6§oAlt§r§3§o to display more.");
        add("tooltip.nine_nether_regions.hellalloy_leggings_alt",
                "§3§oSelf healing: If the durability is not sufficient, the equipment will automatically restore durability in the armor bar or player backpack §1(4 points restored every 2 seconds)§r§3§o.\nSingle effect: When equipped on the armor bar, it continuously provides players with §6jump_boost§r§3§o(effect level:1), while clearing §7nausea§r§3§o effects on the player's body.\nComplete set of effects: Provide a 44% reduction for most damages,force to restore 0.7 point of health for every 10 ticks and provide §6resistance§r§3§o(level 2) effect.");
        add("tooltip.nine_nether_regions.hellalloy_leggings", "§8§oPress§r §3§oAlt§r§8§o to display more.");
        add("tooltip.nine_nether_regions.hellalloy_boots_alt",
                "§3§oSelf healing: If the durability is not sufficient, the equipment will automatically restore durability in the armor bar or player backpack §1(4 points restored every 2 seconds)§r§3§o.\nSingle effect: When equipped on the armor bar, it continuously provides players with §6speed§r§3§o(effect level:2), while clearing §7slowness§r§3§o effects on the player's body.\nComplete set of effects: Provide a 44% reduction for most damages,force to restore 0.7 point of health for every 10 ticks and provide §6resistance§r§3§o(level 2) effect.");
        add("tooltip.nine_nether_regions.hellalloy_boots", "§3§oPress§r §6§oAlt§r§3§o to display more.");
        add("tooltip.nine_nether_regions.styx_helmet", "§6§lMay the Power of Styx be with you.\n§r§8§oPress§r §3§oAlt§r§8§o to display more.");
        add("tooltip.nine_nether_regions.styx_chestplate", "§6§lMay the Power of Styx be with you.\n§r§8§oPress§r §3§oAlt§r§8§o to display more.");
        add("tooltip.nine_nether_regions.styx_leggings", "§6§lMay the Power of Styx be with you.\n§r§8§oPress§r §3§oAlt§r§8§o to display more.");
        add("tooltip.nine_nether_regions.styx_boots", "§6§lMay the Power of Styx be with you.\n§r§8§oPress§r §3§oAlt§r§8§o to display more.");
        add("tooltip.nine_nether_regions.styx_helmet_alt",
                "§6§oIndestructible:§r§3§oUnder normal circumstances, the durability of this equipment will not be depleted. If the durability of the equipment is damaged by some means, its durability will quickly recover (42 points restored every 4 ticks)\n§r§6§oFull Set Effect - Immovable as Mountains:§r§3§oWhen original damage ≤3 points or of type §r§5§oMagic, §r§e§oExplosion, §r§3§oFreeze, §r§1§oWarden's Sonic Boom§r§3§o, forcibly reduces damage to 0; continuously provides §r§6§oResistance Boost and Damage Absorption§r§3§o effects (all effects level 3); forcibly restores 1.5 health point every 10 ticks and provides 75% all damage reduction.\n§r§6§oSingle Piece Effect:§r§3§oContinuously provides §r§6§oNight Vision, Water Breathing, Saturation§r§3§o effects (all effects level 2), and grants immunity to §7§oBlindness, Darkness, Hunger, Bloodblade Curse§r§3§o effects.");
        add("tooltip.nine_nether_regions.styx_chestplate_alt",
                "§6§oIndestructible:§r§3§oUnder normal circumstances, the durability of this equipment will not be depleted. If the durability of the equipment is damaged by some means, its durability will quickly recover (42 points restored every 4 ticks)\n§r§6§oFull Set Effect - Immovable as Mountains:§r§3§oWhen original damage ≤3 points or of type §r§5§oMagic, §r§e§oExplosion, §r§3§oFreeze, §r§1§oWarden's Sonic Boom§r§3§o, forcibly reduces damage to 0; continuously provides §r§6§oResistance Boost and Damage Absorption§r§3§o effects (all effects level 3); forcibly restores 1.5 health point every 10 ticks and provides 75% all damage reduction.\n§r§6§oSingle Piece Effect:§r§3§oContinuously provides §r§6§oFire Resistance, Haste§r§3§o effects (all effects level 2) and §r§6§oStrength§r§3§o effect (level 3), and grants immunity to §7§oWither, Poison, Mining Fatigue, Weakness§r§3§o effects.");
        add("tooltip.nine_nether_regions.styx_leggings_alt",
                "§6§oIndestructible:§r§3§oUnder normal circumstances, the durability of this equipment will not be depleted. If the durability of the equipment is damaged by some means, its durability will quickly recover (42 points restored every 4 ticks)\n§r§6§oFull Set Effect - Immovable as Mountains:§r§3§oWhen original damage ≤3 points or of type §r§5§oMagic, §r§e§oExplosion, §r§3§oFreeze, §r§1§oWarden's Sonic Boom§r§3§o, forcibly reduces damage to 0; continuously provides §r§6§oResistance Boost and Damage Absorption§r§3§o effects (all effects level 3); forcibly restores 1.5 health point every 10 ticks and provides 75% all damage reduction.\n§r§6§oSingle Piece Effect:§r§3§oContinuously provides §r§6§oJump Boost§r§3§o effect (level 2) and §r§6§oLuck§r§3§o effect (level 3), and grants immunity to §7§oNausea§r§3§o effect.");
        add("tooltip.nine_nether_regions.styx_boots_alt",
                "§6§oIndestructible:§r§3§oUnder normal circumstances, the durability of this equipment will not be depleted. If the durability of the equipment is damaged by some means, its durability will quickly recover (42 points restored every 4 ticks)\n§r§6§oFull Set Effect - Immovable as Mountains:§r§3§oWhen original damage ≤3 points or of type §r§5§oMagic, §r§e§oExplosion, §r§3§oFreeze, §r§1§oWarden's Sonic Boom§r§3§o, forcibly reduces damage to 0; continuously provides §r§6§oResistance Boost and Damage Absorption§r§3§o effects (all effects level 3); forcibly restores 1.5 health point every 10 ticks and provides 75% all damage reduction.\n §r§6§oSingle Piece Effect:§r§3§oContinuously provides §r§6§oSpeed§r§3§o effect (level 3), and grants immunity to §7§oSlowness, Levitation, Infested§r§3§o effects, while also providing 100% resistance to fall damage.");
        add("tooltip.nine_nether_regions.hellalloy_longbow", "§3§oMore precise,more powerful.");
        add("tooltip.nine_nether_regions.reinforced_obsidian", "§3§oIt's REALLY hard...It must have some purpose.");
        add("tooltip.nine_nether_regions.ender_staff", "§3§oDraws upon the teleportation power of Ender Pearls, enhanced by a Nether Star.\\nRight-click to teleport to the location pointed by the crosshair, with a maximum range of 64 blocks.");
        add("tooltip.nine_nether_regions.fire_staff", "§3§oSurrounded by flames from the Nether. \nRight-click to launch a Blaze fireball.");
        add("tooltip.nine_nether_regions.wither_staff", "§3§oCondenses the destructive power of the Wither.\nRight-click to launch a black wither skull.");
        add("tooltip.nine_nether_regions.void_staff", "§3§oInfused with power from the Void and the great dragon.\nRight-click to launch a dragon fireball.");
        add("tooltip.nine_nether_regions.rainbowgem", "§3§oA strange gem formed by the fusion of various gems, extremely hard and nearly rivaling Netherite.");
        add("tooltip.nine_nether_regions.ruby_sword", "§3§oA bloodthirsty sword that deals decent damage, at the cost of being extremely fragile.");
        add("tooltip.nine_nether_regions.styx_lamp", "§3§oA lamp that can be toggled on and off. Right-click to switch its state. When lit, creatures will no longer spawn within a radius of 64 blocks centered on it.\n §r§4§oImportant Note: If the lamp is already lit when entering the world, its creature-spawning suppression will not be active! This effect will function normally after toggling it once.");
        add("tooltip.nine_nether_regions.fluoroscopy_block", "§3§oA special block formed by fusing and compressing several transparent blocks, which may be used to locate hidden ores and structures underground…");
        add("tooltip.nine_nether_regions.voidrite_ingot", "§3§oCondenses the myriad powers of the Void into a single ingot.");
        add("tooltip.nine_nether_regions.voidrite_upgrade_smithing_template", "§3Voidrite Upgrade");
    }
}
